server:
  port: 8083

spring:
  application:
    name: USER-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 2311
    url: jdbc:postgresql://localhost:5432/user_db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nodirbekomonboyev2311@gmail.com
    password: ecvumklbihdbpahi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      default-url: ${EUREKA_URI:http://localhost:8761/eureka/}
    instance:
      preferIpAddress: true

logging:
  level:
    org.springframework.cloud: DEBUG
    com.netflix.eureka: DEBUG


